@echo off

if "%PYTHON_EXE%"=="" set PYTHON_EXE=.venv\Scripts\python.exe

if "%DESKTOP_INFERENCE_PORT%"=="" set DESKTOP_INFERENCE_PORT=8001
if "%MAC_INFERENCE_PORT%"=="" set MAC_INFERENCE_PORT=8001
if "%APP_BACKEND_BASE_URL%"=="" set APP_BACKEND_BASE_URL=http://127.0.0.1:8000
if "%APP_BACKEND_TOKEN%"=="" set APP_BACKEND_TOKEN=dev-inference-token
if "%ACTION_ARTIFACTS_DIR%"=="" set ACTION_ARTIFACTS_DIR=training_data\action_pipeline_aihub\inference_artifacts\current

if "%ACCEL_DEVICE%"=="" set ACCEL_DEVICE=cpu
if "%YOLO_DEVICE%"=="" set YOLO_DEVICE=cpu
if "%STT_DEVICE%"=="" set STT_DEVICE=cpu
if "%STT_COMPUTE_TYPE%"=="" set STT_COMPUTE_TYPE=int8

if "%PERSON_IMGSZ%"=="" set PERSON_IMGSZ=640
if "%PERSON_SCORE%"=="" set PERSON_SCORE=0.25
if "%PERSON_DETECTOR_MODEL%"=="" set PERSON_DETECTOR_MODEL=yolo26s.pt
if "%PERSON_POSE_MODEL%"=="" set PERSON_POSE_MODEL=yolo26s-pose.pt

if "%ACTION_INTERVAL%"=="" set ACTION_INTERVAL=1.0
if "%ACTION_RGB_FRAMES%"=="" set ACTION_RGB_FRAMES=16
if "%ACTION_IMAGE_SIZE%"=="" set ACTION_IMAGE_SIZE=112
if "%ACTION_CLIP_SECONDS%"=="" set ACTION_CLIP_SECONDS=4
if "%ACTION_NORMAL_THRESHOLD%"=="" set ACTION_NORMAL_THRESHOLD=0.86
if "%ACTION_MIN_CONFIDENCE%"=="" set ACTION_MIN_CONFIDENCE=0.45

if "%UPLOAD_MAX_FPS%"=="" set UPLOAD_MAX_FPS=24
if "%UPLOAD_FRAME_WIDTH%"=="" set UPLOAD_FRAME_WIDTH=1120
if "%UPLOAD_JPEG_QUALITY%"=="" set UPLOAD_JPEG_QUALITY=72
